# Site settings
title: 'BOAT Stakepool' # Your Title
tagline: 'A rising tide lifts all boats' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: /strange_case # the subpath of your site, e.g. /blog/
